"""cmail bridge — stevejobless (registry) <-> cmail (comms bus).

Direction 1 (sync): steve `projects` table is source of truth for
businesses. This generates idempotent D1 SQL seeding cmail domains,
default mailboxes, and aliases. Apply with:
  wrangler d1 execute cmail-index --remote --file=bridge/seed.sql

Direction 2 (webhook): cmail POSTs important inbound mail to steve
POST /api/observations/email (see stevejobless/stevejobless/email_routes.py).
"""
from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

# Default mailboxes per business. `agents@` routes to Workers AI with
# tenant R2/D1 context; others are human mailboxes.
DEFAULT_BOXES = [
    ("hello", '["READ","DRAFT"]', None),
    ("support", '["READ","DRAFT"]', None),
    ("billing", '["READ","DRAFT"]', None),
    ("agents", '["READ","DRAFT","INTERNAL_ACTION"]', "tenant-agent"),
]

# Pilot: only Cloudflare-managed zones get Email Routing. Others
# (feedify.dev etc. on Name.com) stay on Zoho until migrated.
# Override with CMAIL_CF_ZONES="a.com,b.com".
import os

CF_ZONES = set(
    (os.getenv("CMAIL_CF_ZONES") or
     "egoic.ai,freak.town,intelligentothers.xyz,moltwork.com,ochema.xyz,sanskrit.help,tantrafiles.xyz"
     ).split(",")
)


def build_seed(steve_db: Path) -> str:
    con = sqlite3.connect(steve_db)
    projects = list(con.execute("select slug, name, domain from projects"))
    lines = ["-- generated by bridge/sync.py -- idempotent"]
    for slug, name, domain in projects:
        if not domain:
            continue
        routable = "ready" if domain in CF_ZONES else "external-zoho"
        lines.append(f"INSERT OR IGNORE INTO domains (domain,status) VALUES ('{domain}','{routable}');")
        for local, perms, agent in DEFAULT_BOXES:
            addr = f"{local}@{domain}"
            lines.append(
                "INSERT OR IGNORE INTO mailboxes (id,domain,local_part,address,agent,permissions) "
                f"VALUES ('{addr}','{domain}','{local}','{addr}',"
                + ("NULL" if agent is None else f"'{agent}'") + f",'{perms}');"
            )
        # catch-all conveniences → support, mirroring AgentMail.mx alias_targets
        for alias_local in ("info", "contact", "hi"):
            lines.append(
                "INSERT OR REPLACE INTO aliases (alias,target_mailbox) "
                f"VALUES ('{alias_local}@{domain}','support@{domain}');"
            )
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    steve_db = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/root/stevejobless/stevejobless.db")
    out = Path(__file__).parent / "seed.sql"
    out.write_text(build_seed(steve_db))
    print(f"wrote {out}")
