from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from .models import Project


def passport(name: str, domain: str, repo: str, bundle: str, socials: dict[str, dict], assets: dict[str, bool]) -> dict:
    resources = [
        {"key": "domain", "kind": "domain", "label": "Domain", "desired": {"domain": domain}},
        {"key": "website", "kind": "website", "label": "Production website", "desired": {"url": f"https://{domain}"}},
        {"key": "github", "kind": "github_repo", "label": "GitHub repository", "desired": {"repo": repo}},
        {"key": "appstore", "kind": "app_store", "label": "App Store Connect", "desired": {"app_name": name, "bundle_id": bundle, "app_store_id": None}},
    ]
    for platform, state in socials.items():
        resources.append({"key": f"social:{platform}", "kind": "social", "label": platform.title(),
                          "desired": {"platform": platform, **state}})
    for label, done in assets.items():
        key = "asset:" + label.lower().replace(" ", "_")
        if label in {"Privacy policy", "Terms"}:
            filename = "privacy.md" if label == "Privacy policy" else "terms.md"
            title = "Privacy Policy" if label == "Privacy policy" else "Terms of Service"
            content = f"# {title}\n\nProduct: {name}\nWebsite: https://{domain}\n\nDraft generated by SteveJobless. Replace placeholders and obtain appropriate legal review before publication.\n\n## Contact\n\nAdd the canonical support email here.\n"
            resources.append({"key": key, "kind": "local_artifact", "label": label,
                              "desired": {"path": f"generated/{name.lower()}/{filename}", "content": content}})
        else:
            resources.append({"key": key, "kind": "static", "label": label,
                              "desired": {"label": label, "done": done, "executor": "HUMAN"}})
    return {"version": 1, "product": {"name": name, "domain": domain}, "resources": resources}


SEEDS = [
    ("drawdle", "Drawdle", "drawdle.dev", "prx0r/drawdle", "dev.drawdle.app",
     {"x": {"handle": "drawdle", "state": "unknown"}, "instagram": {"handle": None}, "tiktok": {"handle": None}},
     {"App icon": True, "Privacy policy": False, "Terms": False, "App screenshots": False}),
    ("feedify", "Feedify", "feedify.dev", "prx0r/feedify", "dev.feedify.app",
     {"x": {"handle": "feedifydev", "state": "unknown"}, "instagram": {"required": False}, "tiktok": {"required": False}},
     {"App icon": False, "Privacy policy": False, "Terms": False, "App screenshots": False}),
    ("breadup", "Breadup", "breadup.dev", "prx0r/breadup", "dev.breadup.app",
     {"x": {"handle": None}, "instagram": {"required": False}, "tiktok": {"required": False}},
     {"App icon": False, "Privacy policy": False, "Terms": False, "App screenshots": False}),
]


def seed(db: Session) -> None:
    for slug, name, domain, repo, bundle, socials, assets in SEEDS:
        existing = db.scalar(select(Project).where(Project.slug == slug))
        if existing:
            continue
        db.add(Project(slug=slug, name=name, domain=domain, passport=passport(name, domain, repo, bundle, socials, assets)))
    db.commit()
    _seed_tradie_kernel(db)


def _seed_tradie_kernel(db: Session) -> None:
    """Tradie demo businesses + kernels from the shared YAMLs (one file drives
    voice BUSINESS_CONFIG and the brain kernel — never fork them)."""
    from pathlib import Path

    from .tradie import TradieKernel

    tenants = [
        ("sparky", "Sparky Electrical", "sparkyelectrical.co.uk", "sparky_electrician_en.yaml",
         [{"key": "channel:whatsapp", "kind": "channel", "label": "WhatsApp", "desired": {"state": "stub"}},
          {"key": "channel:voice", "kind": "channel", "label": "Voice agent", "desired": {"state": "compat"}}]),
        ("flowright", "FlowRight Plumbing", "flowrightplumbing.co.uk", "flowright_plumbing_en.yaml",
         [{"key": "channel:whatsapp", "kind": "channel", "label": "WhatsApp", "desired": {"state": "stub"}}]),
    ]
    for slug, name, domain, yaml_file, resources in tenants:
        project = db.scalar(select(Project).where(Project.slug == slug))
        if project is None:
            project = Project(slug=slug, name=name, domain=domain,
                              passport={"version": 1, "product": {"name": name},
                                        "resources": resources})
            db.add(project)
            db.flush()
        if db.scalar(select(TradieKernel).where(TradieKernel.project_id == project.id)) is None:
            import yaml
            cfg = yaml.safe_load((Path(__file__).parent / "knowledge" / yaml_file).read_text())
            tradie_cfg = cfg.get("tradie", {})
            tradie_cfg.setdefault("hours", (cfg.get("business") or {}).get("hours", {}))
            tradie_cfg.setdefault("autonomy", "observe")
            tradie_cfg.setdefault("retention_days", 90)
            db.add(TradieKernel(project_id=project.id, config=tradie_cfg))
    db.commit()
